# -*- coding: utf-8 -*-
"""firstcode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1APLAp7abpApclTbKzkQc3GErKzWFBvga
"""

# print("hello")

#print('hello')

# print("i'm anas emad")

# print('anas')

# print("i'm anas emad")

print('hello it"s me')

print("hi","aianddatascience","zoom")

# print("hi")
# print("ai and data science")
# print("29-12-2025")
# print("zoom")

# first_name="anas"
# second_name='emad'

# one=1
# One=1
# ONE=1

# print("first_name+second_name")

# print(first_name + " "+second_name)

# print("anas|")

a=3
b=a
b=b+3
print(a)
print(b)
print(a+b)

# name="ali"
# last_name='ali'
# #########################
# name="my name's ali"

# last_name='my name"s ali'

# last_name ='''   name's ali"emad  '''
# last_name2 ="""    ''' name's ali"emad '''  """

# print(last_name)

# print(last_name2)

# print(type(name))
# print(type(last_name))

# print(name)
# print(last_name)

# print("anas")

# x=5
# print(x)
# x=20
# print(x)
# x="omar"
# print(x)

# print(5+5)  # sum

# print(10-2)  # subtract

# print(2*3)  # multiply

# print(2**3)  # power

# gpa=3.8
# print(gpa)

# print(17 / 3)   # division

# print(17  //  3)   # floor division    ->> result is integer not decimal

# print(10 % 2)  # moduls   --> reminder

# print(11%2)

# print(type(gpa))

# gpa=4
# print(gpa)

# print(type(gpa))

# print('3+5')

# print(3+5)

# print(type(17/3))

# print(17/3)

# age=30
# gpa=3.8
# name='anas'
# print(age," ",gpa)

# """**BOOL data type**"""

# bo=False    # 0
# bo_1=True   # 1
# print(bo)
# print(type(bo))
# print(type(bo_1))
# print(bo_1)

# # sum
# numberone=10
# numbertwo=20

# add=numberone + numbertwo
# print(type(add))
# print(add)

# # case senseteve
# numberone=10
# numbertwo=20

# add=Numberone+numberTwo
# print(type(add))
# print(add)

# number_1=10.5
# number_2=20
# add=number_1+number_2
# print(add) # sum
# print(type(add))

# number_1=30
# number_2=20
# sub=number_1 - number_2
# print(sub) # sub
# print(type(sub))

# number_1=30
# number_2=20
# multi=number_1*number_2
# print(multi) # multi
# print(type(multi))

# number_1=30
# number_2=20
# div=number_1 / number_2
# print(div) # div
# print(type(div))

# number_1=30
# number_2=20
# div=number_1 // number_2
# print(div) # floor div
# print(type(div))

# number_1=2
# number_2=3
# pow=number_1 ** number_2
# print(pow) # power
# print(type(pow))

# number_1=11
# number_2=2
# mod=number_1 % number_2
# print(mod) # mod
# print(type(mod))

# name='anas'
# print(name)
# print(type(name))

# name=input('Enter Ur Name:')              # for user
# print(name)
# print(type(name))

# number=input() # for user  defult func input is str
# print(number)
# print(type(number))

# numone=input('enter first number:')
# numtwo=input('enter second number:')
# add=numone+numtwo
# print(add)

# numone=int(input('enter first number:'))   # convert str to int
# numtwo=int(input('enter second number:'))
# add=numone+numtwo
# print(add)

# price_of_product=float(input('enter price of product:'))
# total_cost=price_of_product+(price_of_product*0.14)
# print("this is total cost:",total_cost,"$")

# grade_1=float(input('enter grade_1:'))
# grade_2=float(input('enter grade_2:'))
# grade_3=float(input('enter grade_3:'))
# avg=(grade_1+grade_2+grade_3)/3
# print(avg)

# name=input("enter ur name: ")
# gpa=float(input("enter ur gpa: "))
# print(name," ",gpa)

# num=int(input("enter any number:"))
# if num%2==0:
#   print("the number is even")
# else:
#   print("the number is odd")

# num1=float(input("enter first number:"))
# num2=float(input("enter second number:"))
# num3=float(input("enter third number:"))
# sum=num1+num2+num3
# avg=sum/3
# print("sum:",sum,"  ", "avg:",avg)

# gpa1 = float (input("enter your gpa1"))
# gpa2 = float (input("enter your gpa2"))
# gpa3 = float (input("enter your gpa3"))
# average = (gpa1 + gpa2 + gpa3) / 3
# print (average)



