# # -*- coding: utf-8 -*-
# """Strings.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/1K1jvzHpCrAtzJqnWBprGqZFGz_jcPPWK

# # Strings
# """

# hi='hello there'
# name='ana'
# great=hi+"    "+name+"from ai course"
# print(great)

# name='rasha'
#      #01234
# print(name[2])
# print(name[3])

# shahd = "Indore"
# print(shahd)
# print(shahd[0])

# s = "A"
# print(s)
# print(type(s))

# a = "10.5"
# print(type(a))

# print("10.5"+"10") # as string

# x=5
# x='AI'

# #        -1
# s = "Indore"
# #    012345
# print(s[0])
# print(s[0:3:3])

# s='Q'+s[1:]
# s

# s[0]='Q'   # as string immutable

# print('Q'+s)

# s='Indore'
# # 012345

# s[3]

# s[0:3]

# print(s)
# s=s[:3]+'H'+s[4:]   # Ind + H + re
# print(s)

# s[start: stop : step]
# s[::]

# print(s[-1])

# s[::-1]  # reverse

# s

# s[::-3]  # reverse

# s='kerolosmoheb'
# s[::-3]

# l = [1,2]   # mutable
# l[0] = 10
# print(l)

# s = "Indore"         # immutable objects
# s[0] = "A"

# s = "Indore"
# s = "A"
# print(s)

# 1 + 1 = 2 # int - immutable

# 1+1==2

# """# String Slicing"""

# Name = "Shahd"
# print(Name[1])

# s = "Communication"
# #    0123456789

# print(s[1:4])

# print(s[4:1])  # we must add step negative number

# print(s[4:1:-2])

# s = "Communication"
# #    0123456789
# # -1

# s[-9:4]

# s[-9]

# s[4]

# s[-9:3:-1]

# s[-9:5]

# s

# s[5:-4]

# s[-9:-4]
# # unica

# s[-1:-9:-1]

# name =input("Enter your name : ")
# print(name)
# print("Revers : " , name[::-1])

# s[-1:4:-1]
           
















# s

# s[start:end:step]

# s[1:6:2] #steps

# s[::-1]

# s

# n = len(s)
# print(n)

# print(s[n])  # s[13]

# s

# print(s[1:4:-1])

# print(s[4:1:-1])

# print(s[::])  # = s  or [0:n-1:1]

# """# String Functions"""

# s = "India"

# print(len(s))

# A - 65  # ASCII
# B - 66

# Z - 96

# a - 97
# z - 122


# space - 32

# a - 97
# z - 122

score = 90
print("your score is ",score,"to 100")

# name="mahmoud"
# age=25

# print(f'my name is {name} and my age is {age}')
# print("my name is " , name, " and my age is " , age )

# l=[20,30,40,100]
# print(max(l))

# print(max('rasha'))

# print(min('rasha'))

# print(s)
# print(max(s)) # India -> 20 50 3 1 15

# print(min(s))

# print(hi)

# "A" + "B"

# print("a"*3)

# print(sum(s))

# s = '<mohamed>'
# l = ["My",'Name','is',"anas"]

# print(s.join(l))
# print(" ".join(l))

# l = ["My",'Name','is']
# s = " "
# # print(" ".join(l))
# s=s.join(l)
# print(s)

# """#### replace"""

# s = "mohamed"
# s.replace?

# help(s.replace)

# s= "ali mohamed ali hussein ali ibrahim alis"

# new_s= s.replace("ali","ahmed")
# print(new_s)
# print(s)

# s= "ali mohamed ali hussein ali ibrahim"

# new_s= s.replace("ali","ahmed",1)  # 2  is the number of occuranaced=s to  be repplaced
# print(new_s)

# s= "ali mohamed ali hussein ali ibrahim"

# s=s.replace("ali","khaled")
# print(s)

# r = "This is the best momo"
# # r.replace?
# print(r.replace("momo","tea"))
# print(r)
# print("                  ")
# r = r.replace("momo","tea")
# # print(newR)
# print(r)

# r = "This is the best food, best in the food, I love food"

# print(r.replace("food","good"))  # replace the occurances of the value with tha new value default replace all occurences
# print(r.replace("food","good",1))  # here we replace the first occurance only
# print(r.replace("food","good",2))  # here we replace two occurances (which mean here all occurances cause the occurances is  2 )

# """#### upper and lower"""

# a = "India"
# print(a.upper())
# a=a.upper()
# print(a)

# b="INDIA"
# print(b.lower())
# print(b)

# print(a.lower())

# """#capitalize"""

# s = "mohamed"
# print(s.capitalize()) # it make the first char upper case

# """#### split"""

# r=""
# help(r.split)

# r = "Hello world,AUC,AI"

# print(r.split(","))

# r = "Helloworld egypt"

# print(r.split("wo"))

# r.split?

# r = "Hello world egypt"

# print(r.split())

# r = "This is the best food anas best in the food anas hello from ai course"
# l = r.split("anas")
# print(l)

# h = "abcdef"
# print(h[0]+h[2]+h[3])